name: "fmtcheck"
description: "Enforce consistent formatting across your CI pipeline."
author: "coccinella-labs"
branding:
  icon: "check"
  color: "green"

inputs:
  path:
    description: "Directory to check."
    required: false
    default: "."

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "--path"
    - ${{ inputs.path }}
